name: TNTZones
version: '${project.version}'
build: '${project.build.number}'
main: de.crafttogether.tntzones.TNTZonesPlugin
api-version: 1.13
depend: [WorldEdit]
commands:
  tntzone:
    description: TNTZone-Command
    usage: /tntzone
