name: TNTZones
version: ${project.version}
main: de.crafttogether.tntzones.TNTZonesPlugin
api-version: 1.13
depend: [WorldEdit]
commands:
  tntzone:
    description: TNTZone-Command
    usage: /tntzone
